### ISSUE TITLE
If private registry set in .npmrc, get 404 for cli-utils when trying to install webpack-serve.

### ISSUE THREAD

**Issue by brekt** [webpack-contrib/cli-utils#1]
* Operating System: OSX 10.13.5 High Sierra
* Node Version: tried 8.11.3 and 10.8.0
* NPM Version: 6.3.0
* webpack Version: 4.16.5
* webpack-serve Version: latest as of Tuesday 8/7/2018

### Expected Behavior

I run `npm i -D webpack-serve` and profit.

### Actual Behavior

I run the above and see
```
npm ERR! code E404
npm ERR! 404 Not Found: @webpack-contrib/cli-utils@^1.0.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mburnett/.npm/_logs/2018-08-07T21_18_22_917Z-debug.log
```

### How Do We Reproduce?
Add a private external registry to .npmrc. Try to install webpack-serve in new project. Alternatively just try to install cli-utils.

### Workaround
Delete private registry from .npmrc and run again. Then add private registry back to .npmrc.

**Comment by liamzdenek** [comment]
I'm experiencing this issue as well. Node 8.9.4, NPM 6.3.0, Ubuntu 16.04. Retrieving different versions of cli-utils does not work. Other packages scoped to `@webpack-contrib` work correctly, eg, `npm install @webpack-contrib/config-loader`. This issue appears specific to this package.

**Comment by spoldman** [comment]
Having the same issue using Artifactory as private npm server.

**Comment by msn0** [comment]
same here

**Comment by msn0** [comment]
setting
```
registry=https://myprivateregistry/....
@webpack-contrib:registry=https://registry.npmjs.org/
```
in `.npmrc` (as described here https://github.com/storybooks/storybook/issues/15) works for me as a workaround.

**Comment by alexander-akait** [comment]
DEPRECATED, please use `webpack-cli` and `webpack-dev-serve`.

Why deprecated `webpack-serve` and `webpack-dev-serve` ?

- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some dependencies are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.

Thanks for using webpack! We apologize for the inconvenience. In the future, we will avoid such situations.
